name: Deploy Converter

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Verify Libraries
        run: |
          if [ ! -f "docs/lib/pdf.min.js" ]; then
            echo "::error::Missing PDF.js library"
            exit 1
          fi
          if [ ! -f "docs/lib/tesseract.min.js" ]; then
            echo "::error::Missing Tesseract.js library"
            exit 1
          fi
          
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
          
      - uses: actions/deploy-pages@v4
