name: Setup Libraries

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  download-libs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for proper Git operations
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download libraries
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Create directories
          mkdir -p docs/lib docs/tessdata
          
          # Download PDF.js
          wget https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js -O docs/lib/pdf.min.js
          wget https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.worker.min.js -O docs/lib/pdf.worker.min.js

          # Download Tesseract.js
          wget https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/4.1.1/tesseract.min.js -O docs/lib/tesseract.min.js
          wget https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/4.1.1/tesseract-core.wasm.js -O docs/lib/tesseract-core.wasm.js
          wget https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/4.1.1/tesseract-worker.min.js -O docs/lib/tesseract-worker.min.js

          # Download docx.js
          wget https://cdnjs.cloudflare.com/ajax/libs/docx/7.8.2/docx.min.js -O docs/lib/docx.min.js

          # Download FileSaver.js
          wget https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js -O docs/lib/FileSaver.min.js

          # Download language data
          wget https://github.com/naptha/tessdata/raw/gh-pages/4.0.0/eng.traineddata -O docs/tessdata/eng.traineddata
          wget https://github.com/naptha/tessdata/raw/gh-pages/4.0.0/fra.traineddata -O docs/tessdata/fra.traineddata
          wget https://github.com/naptha/tessdata/raw/gh-pages/4.0.0/spa.traineddata -O docs/tessdata/spa.traineddata
          wget https://github.com/naptha/tessdata/raw/gh-pages/4.0.0/deu.traineddata -O docs/tessdata/deu.traineddata
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are changes to commit
          git add docs/lib/ docs/tessdata/
          if ! git diff --cached --quiet; then
            git commit -m "Auto-download libraries [skip ci]"
            git push
          else
            echo "No library changes to commit"
          fi
