name: Deploy PDF to Word Converter

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper deployment
          submodules: recursive  # Important for Tesseract.js

      # Step 2: Verify critical files exist
      - name: Validate required files
        run: |
          REQUIRED_FILES=(
            "docs/index.html"
            "docs/script.js"
            "docs/lib/pdf.min.js"
            "docs/lib/tesseract.min.js"
            "docs/tessdata/eng.traineddata"
          )
          
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "::error::Missing required file: $file"
              exit 1
            fi
          done
          echo "✅ All required files present"

      # Step 3: Set up GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      # Step 4: Prepare deployment package
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/"
          retention-days: 1  # Reduces storage usage

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        timeout-minutes: 5  # Prevent hanging deployments
